### PR TITLE
Fix #2169 by correcting shutdown timeout

### LINKED ISSUE #2169: LongPollingTransport shutdown timer is configured incorrectly
https://github.com/aspnet/SignalR/blob/c53514fa19bbb776ee3855a6cfaa1c4706b7f446/clients/ts/signalr/src/LongPollingTransport.ts#L182-L185

[`setTimeout`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) takes the callback as the **first** argument

### PR DESCRIPTION
**Pull request by anurse**
Still thinking about how best to test the Long Polling shutdown timeout case. We don't have any test coverage here yet because of pending #2048 .

Fixes #2169

### CODE REVIEW

**Comment by JamesNK** [comment]
Can we add a unit test the verifies that shutdown timeout works? 😸

**Comment by anurse** [comment]
It's never called in a unit test right now. I think I can actually bash out a test for this. Stand by

**Comment by anurse** [comment]
:up: :date: Unit test!

File: clients/ts/FunctionalTests/ts/HubConnectionTests.ts [hunk 1]
```diff
@@ -577,13 +577,8 @@ describe("hubConnection", () => {
                     const hubConnection = getConnectionBuilder(transportType).build();
                     hubConnection.serverTimeoutInMilliseconds = 100;
 
-                    const timeout = setTimeout(200, () => {
```
Comment (anurse) [inline clients/ts/FunctionalTests/ts/HubConnectionTests.ts]: This was an attempt to get the test to fail sooner than Jasmine's own timeout, but I think it's cleaner to just let Jasmine do it's thing.

File: clients/ts/signalr/spec/LongPollingTransport.spec.ts [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+                    const abort = new Promise((resolve, reject) => r.abortSignal.onabort = resolve);
+                    await abort;
+
+                    // Signal that the poll has completed.
+                    pollCompleted.resolve();
+                    return new HttpResponse(204);
+                }
+            })
+            .on("DELETE", (r) => new HttpResponse(202));
+        const transport = new LongPollingTransport(client, null, NullLogger.instance, false, 100);
```
Comment (JamesNK) [inline clients/ts/signalr/spec/LongPollingTransport.spec.ts]: Do we know this 100 ms timeout is honored because the default 5000 ms timeout will cause the test to timeout?

Comment (anurse) [reply clients/ts/signalr/spec/LongPollingTransport.spec.ts]: Before I added this parameter, the test would flake out. Sometimes it would pass, sometimes it wouldn't, and it was based on the jasmine 5000 ms timeout. It's very consistent with this change so we know it should be honored.
